### ISSUE TITLE
Card ordering system

### ISSUE THREAD

**Issue by petterroea** [phoenixlan/phoenixapi-v1#36]
We need a system that works something like this:

* Chiefs can order the creation of a card for one person, **or an entire crew**
  - Possibly, we only implement order creation for one person, and the rest can be done by the frontend by fetching all members of the crew
* Chiefs and card printers can see a list of all cards that were ordered
* Card printers can generate the crew card for a single member, as PNG
* Card printers can generate the crew cards for an entire crew, as .zip
  - In both cases, we store the files in a temporary directory using some random hash
* When cards are generated(from an order - not from the "generate crew card" feature on a user that we already have today), the order state is changed from "CREATED" to "IN PROGRESS"
* Card printers can mark orders that are printed as "FINISHED"
* The order state should be visible when you list orders
* A chief should be able to cancel orders

# Database objects

## Card order

* The subject of the order
* The creator
* Last updated by
* Last updated (time)
* Created (time)
* State

**Comment by simsine** [comment]
On it.
Should the state column simply be a text type?
