### ISSUE TITLE
Double GDPR message in crew e-mail

### ISSUE THREAD

**Issue by petterroea** [phoenixlan/phoenixapi-v1#54]
Determine why some crew e-mails have double GDPR message at the bottom:

![image](https://github.com/user-attachments/assets/190dce6b-01c0-4474-8ce1-1bf23e4cabb3)

@HenrikEngen any idea?

**Comment by HenrikEngen** [comment]
Oop, I think we forgot to remove the GDPR message when we copied and edited the previous emails we sent in 2023.
I think this because the first message doesnt have a new line for "Spørsmål? info@phoenixlan.no"
I believe nothing is wrong on the server-side.
